# install with conda env create -f environment.yml
# env file is built off the DSCI 575 env file with additional packages for app functionality as needed 
name: 'amazon-recommender'
channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python==3.12
  - ipykernel
  - matplotlib
  - pandas
  - nb_conda_kernels
  - requests
  - ipywidgets
  - plotly
  - jupyter-dash
  - scikit-learn
  - protobuf==4.25.3
  - torchvision
  - torchaudio
  - pytorch
  - autograd
  - wordcloud
  - seaborn
  - sentence-transformers
  - nltk
  - hmmlearn
  - wikipedia
  - spacy
  - panel
  - python-dotenv
  - scipy
  - librosa
  - networkx
  - python-graphviz
  - pygraphviz
  - pydot
  - pip
  - duckdb
  - duckdb-python
  - fastparquet
  - pip:
    - torch-summary
    - otter-grader
    - kaleido
    - pyppeteer
    - mglearn
    - transformers
    - langchain
    - langchain-core
    - langchain-community
    - langchain-openai
    - langchain-groq
    - langchain-google-genai
    - langchain-anthropic
    - langchain-huggingface
    - faiss-cpu
    - langchain-chroma>=0.1.2
    - mcp
    - langchain-mcp-adapters
    - langchain-text-splitters
    - pypdf
    - streamlit>=1.56.0
    - rank_bm25>=0.2.2
    - sentence-transformers